### ISSUE TITLE
How do I use Pi-hole with PiVPN - docs clarification

### ISSUE THREAD

**Issue by planetahuevo** [pivpn/docs#11]
It would be great to edit that area based on this conversation:
https://github.com/pivpn/pivpn/issues/1340

**Comment by 4s3ti** [comment]
Well it seems quite clear and easy to understand to me, but I am not English native, so if you have a better way please feel free to suggest it. 

If you don't know how to make a Pull request, its fine just mention here what you think would be best.

**Comment by planetahuevo** [comment]
I think this could work to clarify the docs. 
After this: 

> "Note that if you install PiVPN after Pi-hole, your existing Pi-hole installation will be detected and the script will ask if you want to use it as the DNS for the VPN, so you won't need to go through all these steps. 

You could add something like this:

> If you use the script, pivpnDNS1 value will be "10.6.0.1" which is the VPN internal IP. When doing it manually it is easier for to find the local ip of the raspberry pi instead of the VPN internal IP and since pihole is listening on all interfaces both values are correct.

PS: not everyone knows how to do a Pull request. Creating issues is also a way to collaborate, but I can see you are not happy so I will leave it here and not disturb you anymore. 

Good luck with your project. I hope you find other developers to help you. 
Best regards

**Comment by 4s3ti** [comment]
any sugestions @orazioedoardo ? this suggestion seems even more confusing to me, however i agree it could be improved somehow.

**Comment by orazioedoardo** [comment]
@planetahuevo When the script prompts the user to use Pi-hole with PiVPN, it automatically uses the 10.6.0.1 IP and not the LAN IP because the LAN IP is detected by the script only on a Raspberry Pi, and you may not have a LAN IP at all if you are installing on a virtual private server. So, actually it would make more sense that the docs suggest 10.6.0.1 (and 10.8.0.1 for openvpn).

**Comment by 4s3ti** [comment]
Pre-archive closing, more information [here](https://github.com/pivpn/pivpn/releases/tag/v4.6.0)
